# Generated by Django 3.1.2 on 2020-10-23 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='items.item')),
                ('messenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_messenger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
