# Generated by Django 3.1.2 on 2020-10-23 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_owner'),
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='items.item'),
        ),
    ]
