# Generated by Django 3.1.2 on 2020-10-25 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0002_auto_20201023_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='messenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
